Repository ivy-llc/ivy, pull requests merged in 2022-08, with the labels that each got.

#2532 container legacy method `stop_gradients` to equivalent `stop_gradient` method in `ivy/container/gradients.py`
  ivy/array/gradients.py
  ivy/container/base.py
  ivy/container/gradients.py
  ivy/functional/ivy/meta.py
  ivy/stateful/module.py
  ivy_tests/test_ivy/test_container.py
Labels: with CI

#2556 container legacy method `to_device` to equivalent method in `ivy/container/device.py`
  ivy/array/device.py
  ivy/container/base.py
  ivy/container/device.py
  ivy_tests/test_ivy/test_container.py
Labels: with CI

#2349 Searching Fix Up
  .github/workflows/test-fn-searching-jax.yml
  .github/workflows/test-fn-searching-np.yml
  .github/workflows/test-fn-searching-tf.yml
  .github/workflows/test-fn-searching-torch.yml
  ivy/array/searching.py
  ivy/container/searching.py
  ivy/functional/backends/jax/searching.py
  ivy/functional/backends/numpy/searching.py
  ivy/functional/backends/tensorflow/searching.py
  ivy/functional/backends/torch/searching.py
  ivy/functional/ivy/searching.py
  ivy_tests/test_ivy/test_functional/test_core/test_searching.py
Labels: with CI

#1999 Container operators
  docs/partial_source/deep_dive/5_containers.rst
  ivy/container/base.py
  ivy/container/container.py
  ivy/functional/backends/jax/elementwise.py
  ivy/functional/ivy/elementwise.py
  ivy/functional/ivy/nest.py
Labels: with CI

#2418 reformatted arg_names #2410
  ivy/functional/ivy/general.py
Labels: with CI

#2583 Fix `erf` tests
  ivy/functional/backends/numpy/elementwise.py
Labels: with CI

#2540 added abs function and tests to pytorch frontend
  ivy/functional/frontends/torch/pointwise_ops.py
  ivy_tests/test_ivy/test_frontends/test_torch/test_pointwise_ops.py
Labels: with CI

#2570 Fix Set tests tensorflow
  ivy/functional/backends/tensorflow/set.py
  ivy_tests/test_ivy/test_functional/test_core/test_set.py
Labels: with CI

#2602 Creation functions fixup
  ivy_tests/test_ivy/test_functional/test_core/test_creation.py
Labels: with CI

#2516 Type promotion fixes
  ivy/__init__.py
  ivy/functional/backends/jax/creation.py
  ivy/functional/backends/jax/elementwise.py
  ivy/functional/backends/jax/linear_algebra.py
  ivy/functional/backends/jax/sorting.py
  ivy/functional/backends/mxnet/elementwise.py
  ivy/functional/backends/mxnet/manipulation.py
  ivy/functional/backends/mxnet/sorting.py
  ivy/functional/backends/numpy/elementwise.py
  ivy/functional/backends/numpy/layers.py
  ivy/functional/backends/numpy/linear_algebra.py
  ivy/functional/backends/numpy/sorting.py
  ivy/functional/backends/tensorflow/elementwise.py
  ivy/functional/backends/tensorflow/layers.py
  ivy/functional/backends/tensorflow/linear_algebra.py
  ivy/functional/backends/tensorflow/manipulation.py
  ivy/functional/backends/tensorflow/sorting.py
  ivy/functional/backends/torch/creation.py
  ivy/functional/backends/torch/elementwise.py
  ivy/functional/backends/torch/layers.py
  ivy/functional/backends/torch/linear_algebra.py
  ivy/functional/backends/torch/manipulation.py
  ivy/functional/backends/torch/sorting.py
  ivy/functional/ivy/data_type.py
  ivy/functional/ivy/device.py
  ivy/functional/ivy/elementwise.py
  ivy/functional/ivy/linear_algebra.py
  ivy/functional/ivy/manipulation.py
  ivy/functional/ivy/sorting.py
  ivy_tests/test_ivy/helpers.py
Labels: with CI

#2662 update cont `to_list` to `to_nested_list`
  ivy/container/base.py
Labels: with CI

#2668 Creation fixes
  ivy/functional/backends/torch/creation.py
  ivy/functional/ivy/creation.py
  ivy_tests/test_ivy/test_functional/test_core/test_creation.py
Labels: with CI

#2616 Reformat copy_nest
  ivy/functional/ivy/nest.py
Labels: Reformatting

#2571 Fixed the formatting issue
  ivy/functional/frontends/tensorflow/functions.py
  ivy_tests/test_ivy/test_frontends/test_tensorflow/test_tf_functions.py
Labels: with CI

#2473 reformatting get_min_base
  ivy/functional/ivy/general.py
Labels: Reformatting

#2156 Map
  ivy/functional/ivy/nest.py
Labels: Sub Task

#2661 Docstring
  ivy/array/layers.py
  ivy/container/elementwise.py
  ivy/container/layers.py
  ivy/container/linear_algebra.py
  ivy/functional/backends/mxnet/elementwise.py
  ivy/functional/backends/tensorflow/elementwise.py
  ivy/functional/frontends/jax/lax/operators.py
  ivy/functional/frontends/numpy/sorting_searching_counting/searching.py
  ivy/functional/ivy/data_type.py
  ivy/functional/ivy/elementwise.py
  ivy/functional/ivy/general.py
  ivy/functional/ivy/layers.py
  ivy/functional/ivy/linear_algebra.py
  ivy/functional/ivy/manipulation.py
  ivy/functional/ivy/nest.py
  ivy_tests/test_docstrings.py
Labels: Sub Task

#2561 Elementwise fixups
  ivy/container/elementwise.py
  ivy/functional/backends/jax/elementwise.py
  ivy/functional/backends/numpy/elementwise.py
  ivy/functional/backends/tensorflow/elementwise.py
  ivy/functional/backends/torch/elementwise.py
  ivy_tests/test_ivy/test_functional/test_core/test_elementwise.py
Labels: with CI

#2255 Refactor Matmul
  ivy/array/linear_algebra.py
  ivy/container/linear_algebra.py
  ivy/functional/ivy/linear_algebra.py
Labels: Reformatting

#2750 fix `meta` positional and keyword arguments
  ivy/functional/ivy/meta.py
Labels: with CI

#2614 arcsin [#1525]
  ivy/func_wrapper.py
  ivy/functional/backends/jax/general.py
  ivy/functional/backends/mxnet/general.py
  ivy/functional/backends/numpy/general.py
  ivy/functional/backends/tensorflow/general.py
  ivy/functional/backends/torch/general.py
  ivy/functional/frontends/numpy/mathematical_functions/trigonometric_functions.py
  ivy/functional/ivy/general.py
  ivy_tests/test_ivy/helpers.py
  ivy_tests/test_ivy/test_frontends/test_numpy/helpers.py
  ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_trigonometric_functions.py
Labels: with CI

#2855 Creation linspace fix
  ivy/functional/backends/jax/creation.py
  ivy_tests/test_ivy/test_functional/test_core/test_creation.py
Labels: with CI

#2783 Added asin function to PyTorch frontend
  ivy/functional/frontends/torch/pointwise_ops.py
  ivy_tests/test_ivy/test_frontends/test_torch/test_pointwise_ops.py
Labels: Extension, Next Release, Ivy Functional API

#2895 Searching reformat
  ivy/array/searching.py
  ivy/container/searching.py
  ivy/functional/backends/jax/searching.py
  ivy/functional/backends/numpy/searching.py
  ivy/functional/backends/tensorflow/searching.py
  ivy/functional/backends/torch/searching.py
  ivy/functional/ivy/searching.py
Labels: with CI

#2775 Acos
  ivy/functional/frontends/jax/lax/operators.py
  ivy_tests/test_ivy/test_frontends/test_jax/test_jax_lax_operators.py
Labels: Sub Task

#2984 frontend_torch_gelu
  ivy/functional/frontends/torch/non_linear_activation_functions.py
  ivy_tests/test_ivy/test_frontends/test_torch/test_non_linear_activation_functions.py
Labels: Sub Task

#2891 fix `set` positional and keyword arguments
  ivy/array/set.py
  ivy/container/set.py
  ivy/functional/backends/jax/set.py
  ivy/functional/backends/mxnet/set.py
  ivy/functional/backends/numpy/set.py
  ivy/functional/backends/tensorflow/set.py
  ivy/functional/backends/torch/set.py
  ivy/functional/ivy/set.py
  ivy_tests/test_ivy/test_functional/test_core/test_set.py
Labels: with CI

#2906 Update to args for creation module backends
  ivy/array/creation.py
  ivy/functional/backends/jax/creation.py
  ivy/functional/backends/mxnet/creation.py
  ivy/functional/backends/numpy/creation.py
  ivy/functional/backends/tensorflow/creation.py
  ivy/functional/backends/torch/creation.py
  ivy/functional/ivy/creation.py
  ivy_tests/test_ivy/test_functional/test_core/test_creation.py
Labels: with CI

#2921 handle limits for `int` and `uint` in ivy tests helper
  ivy_tests/test_ivy/helpers.py
Labels: with CI

#3099 Docstrings
  ivy/array/gradients.py
  ivy/container/gradients.py
  ivy_tests/test_docstrings.py
Labels: Sub Task

#3080 Fix for floats generation in ivy tests helper
  ivy_tests/test_ivy/helpers.py
Labels: with CI

#2523 General cumprod
  ivy/array/general.py
  ivy/container/general.py
  ivy/functional/ivy/general.py
Labels: with CI

#3010 added hypothesis framework setting functionality
  .idea/ivy.iml.save
  .idea/vcs.xml
  ivy_tests/test_ivy/conftest.py
  ivy_tests/test_ivy/helpers.py
  ivy_tests/test_ivy/test_frontends/test_jax/test_activations.py
  ivy_tests/test_ivy/test_frontends/test_jax/test_jax_lax_operators.py
  ivy_tests/test_ivy/test_frontends/test_numpy/test_creation_routines/test_from_shape_or_value.py
  ivy_tests/test_ivy/test_frontends/test_numpy/test_manipulation_routines/test_joining_arrays.py
  ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_arithmetic_operations.py
  ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_hyperbolic_functions.py
  ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_trigonometric_functions.py
  ivy_tests/test_ivy/test_frontends/test_numpy/test_sorting_searching_counting/test_searching.py
  ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py
  ivy_tests/test_ivy/test_frontends/test_tensorflow/test_raw_ops.py
  ivy_tests/test_ivy/test_frontends/test_torch/test_creation_ops.py
  ivy_tests/test_ivy/test_frontends/test_torch/test_indexing_slicing_joining_mutating_ops.py
  ivy_tests/test_ivy/test_frontends/test_torch/test_non_linear_activation_functions.py
  ivy_tests/test_ivy/test_frontends/test_torch/test_pointwise_ops.py
  ivy_tests/test_ivy/test_functional/test_core/test_creation.py
  ivy_tests/test_ivy/test_functional/test_core/test_device.py
  ivy_tests/test_ivy/test_functional/test_core/test_dtype.py
  ivy_tests/test_ivy/test_functional/test_core/test_elementwise.py
  ivy_tests/test_ivy/test_functional/test_core/test_general.py
  ivy_tests/test_ivy/test_functional/test_core/test_gradients.py
  ivy_tests/test_ivy/test_functional/test_core/test_linalg.py
  ivy_tests/test_ivy/test_functional/test_core/test_manipulation.py
  ivy_tests/test_ivy/test_functional/test_core/test_random.py
  ivy_tests/test_ivy/test_functional/test_core/test_searching.py
  ivy_tests/test_ivy/test_functional/test_core/test_set.py
  ivy_tests/test_ivy/test_functional/test_core/test_sorting.py
  ivy_tests/test_ivy/test_functional/test_core/test_statistical.py
  ivy_tests/test_ivy/test_functional/test_core/test_utility.py
  ivy_tests/test_ivy/test_functional/test_nn/test_activations.py
  ivy_tests/test_ivy/test_functional/test_nn/test_layers.py
  ivy_tests/test_ivy/test_functional/test_nn/test_losses.py
  ivy_tests/test_ivy/test_functional/test_nn/test_norms.py
Labels: with CI

#3150 numpy floor_divide special case errors resolved
  ivy/functional/backends/numpy/elementwise.py
Labels: with CI

#3173 Non linear jax functions
  .idea/ivy.iml.save
  ivy/array/data_type.py
  ivy/functional/backends/jax/activations.py
  ivy/functional/backends/jax/data_type.py
  ivy/functional/backends/numpy/activations.py
  ivy/functional/backends/tensorflow/activations.py
  ivy/functional/backends/tensorflow/general.py
  ivy/functional/backends/torch/activations.py
  ivy/functional/frontends/jax/nn/non_linear_activations.py
  ivy_tests/test_ivy/helpers.py
  ivy_tests/test_ivy/test_frontends/test_jax/test_activations.py
  ivy_tests/test_ivy/test_frontends/test_jax/test_jax_nn_activations.py
Labels: with CI

#3076 set_min_denominator
  ivy/functional/ivy/general.py
Labels: Sub Task

#2112 completed issue map_nest_at_indices #2104
  ivy/functional/ivy/nest.py
Labels: Stale

#3347 Implement reciprocal in ivy core and add to jax.lax frontend
  ivy/functional/backends/jax/elementwise.py
  ivy/functional/backends/mxnet/elementwise.py
  ivy/functional/backends/numpy/elementwise.py
  ivy/functional/backends/tensorflow/elementwise.py
  ivy/functional/backends/torch/elementwise.py
  ivy/functional/frontends/jax/lax/operators.py
  ivy/functional/ivy/elementwise.py
  ivy_tests/test_ivy/test_frontends/test_jax/test_jax_lax_operators.py
  ivy_tests/test_ivy/test_functional/test_core/test_elementwise.py
Labels: Extension

#3075 Stateful sequential Fixup
  .github/workflows/test-ivy-stateful.yml
  ivy/stateful/sequential.py
  ivy_tests/test_ivy/test_stateful/test_sequential.py
Labels: with CI

#3316 add round to jax
  ivy/functional/frontends/jax/lax/operators.py
  ivy_tests/test_ivy/test_frontends/test_jax/test_jax_lax_operators.py
Labels: Extension, Next Release, Ivy Functional API

#3310 signal
  ivy/functional/frontends/tensorflow/signal.py
  ivy_tests/test_ivy/test_frontends/test_tensorflow/test_signal.py
Labels: Sub Task

#2867 LogicalAnd
  ivy/functional/frontends/tensorflow/math.py
  ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py
Labels: Sub Task

#3710 backend specific dtype handling
  ivy_tests/test_ivy/helpers.py
  ivy_tests/test_ivy/test_functional/test_core/test_creation.py
  ivy_tests/test_ivy/test_functional/test_core/test_device.py
  ivy_tests/test_ivy/test_functional/test_core/test_dtype.py
  ivy_tests/test_ivy/test_functional/test_core/test_elementwise.py
  ivy_tests/test_ivy/test_functional/test_core/test_general.py
  ivy_tests/test_ivy/test_functional/test_core/test_gradients.py
  ivy_tests/test_ivy/test_functional/test_core/test_linalg.py
  ivy_tests/test_ivy/test_functional/test_core/test_manipulation.py
  ivy_tests/test_ivy/test_functional/test_core/test_random.py
  ivy_tests/test_ivy/test_functional/test_core/test_searching.py
  ivy_tests/test_ivy/test_functional/test_core/test_set.py
  ivy_tests/test_ivy/test_functional/test_core/test_sorting.py
  ivy_tests/test_ivy/test_functional/test_core/test_statistical.py
  ivy_tests/test_ivy/test_functional/test_core/test_utility.py
  ivy_tests/test_ivy/test_functional/test_nn/test_activations.py
  ivy_tests/test_ivy/test_functional/test_nn/test_layers.py
  ivy_tests/test_ivy/test_functional/test_nn/test_losses.py
  ivy_tests/test_ivy/test_functional/test_nn/test_norms.py
Labels: with CI

#2774 implementing Tensorflow matrix_rank Frontend function
  ivy/functional/backends/tensorflow/linear_algebra.py
  ivy/functional/backends/torch/linear_algebra.py
  ivy/functional/frontends/tensorflow/linalg.py
  ivy_tests/test_ivy/test_frontends/test_tensorflow/test_linalg.py
  ivy_tests/test_ivy/test_functional/test_core/test_linalg.py
Labels: with CI

#3738 fix `random` tests
  ivy/functional/ivy/manipulation.py
  ivy_tests/test_ivy/test_functional/test_core/test_random.py
  ivy_tests/test_ivy/test_functional/test_core/test_utility.py
  ivy_tests/test_ivy/test_functional/test_nn/test_losses.py
Labels: with CI

#3747 Fix `pow` and `atan2` functional tests
  ivy_tests/test_ivy/test_functional/test_core/test_elementwise.py
Labels: with CI

#3256 Tensorflow Frontend Math Function and Test Implementations
  ivy/functional/frontends/tensorflow/math.py
  ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py
Labels: TensorFlow Frontend

#2079 reformat tile
  ivy/array/manipulation.py
  ivy/container/manipulation.py
  ivy/functional/backends/jax/manipulation.py
  ivy/functional/backends/mxnet/manipulation.py
  ivy/functional/backends/numpy/manipulation.py
  ivy/functional/backends/tensorflow/manipulation.py
  ivy/functional/backends/torch/manipulation.py
  ivy/functional/ivy/manipulation.py
Labels: Reformatting

#3031 Reformat sum #1210
  ivy/functional/backends/jax/statistical.py
  ivy/functional/backends/mxnet/statistical.py
  ivy/functional/backends/numpy/statistical.py
  ivy/functional/backends/tensorflow/statistical.py
  ivy/functional/backends/torch/statistical.py
  ivy/functional/ivy/statistical.py
Labels: Reformatting

#3875 Fix `test_greater` elementwise
  ivy_tests/test_ivy/test_functional/test_core/test_elementwise.py
Labels: with CI

#3882 Array api dashboard
  .github/workflows/test-array-api-jax.yml
  .github/workflows/test-array-api-tensorflow.yml
  .github/workflows/test-array-api-torch.yml
  .github/workflows/test-array-api.yml
  test_array_api.sh
Labels: with CI
